name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Inject API URL
        run: |
          # This replaces the placeholder with your actual secret URL in the JS file
          sed -i 's|API_URL|${{ secrets.sheety_api_url }}|g' app.js

      - name: Deploy to GitHub Pages
        uses: brunorism/github-pages-deploy-action@v4
        with:
          folder: . # The folder your files are in
          branch: master