name: Deploy static content to Pages

on:
    push:
        branches: [ "master" ]

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject API URL
        run: |
          # This replaces the placeholder with your actual secret URL in the JS file
          sed -i 's|API_URL|${{ secrets.SHEETY_URL }}|g' ./app.js

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifacts
        uses: actions/upload-pages-artifacts@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
